### ISSUE TITLE
mac address conflicts at high scale

### ISSUE THREAD

**Issue by rthakur-est** [k8snetworkplumbingwg/ovs-cni#206]
We have a deployment of 100 worker nodes with 24 vlans and 1000 ovs-cni interfaces on each of these vlans.
On few of these vlans, the ovs-cni ends up allocating same mac address to different pods.
Is there any way to avoid duplicate mac address allocation with ovs-cni?

**Comment by pperiyasamy** [comment]
@rthakur-est The PR #205 attempts fix this by deriving mac address from assigned ip address on the container interface, does it fix the issue ?

**Comment by rthakur-est** [comment]
@pperiyasamy This looks good. I will try this out.

**Comment by phoracek** [comment]
@rthakur-est Peri's MAC PR was merged and released as a part of https://github.com/k8snetworkplumbingwg/ovs-cni/releases/tag/v0.24.0. Would you have a chance to verify whether it fixed your problem?

**Comment by rthakur-est** [comment]
@phoracek I have verified it and it seems to work properly.

**Comment by phoracek** [comment]
Fantastic, thanks a lot.
