### ISSUE TITLE
Clean ports after host reboot

### ISSUE THREAD

**Issue by mel1nn** [k8snetworkplumbingwg/ovs-cni#220]
Hi, as described in this [issue](https://github.com/k8snetworkplumbingwg/ovs-cni/issues/106), I'm facing a problem on an OVS bridge after a restart of the node that hosts the pod (connected to the ovs bridge). A new port is added to the bridge (new interface of the container) but the older still exists and is in error state. 

By calling the cleanPorts function in the cmdAdd function (pkg/plugin/plugin.go) may fix the problem.

Thanks for your help.

**Comment by phoracek** [comment]
Hello, thanks for reporting this. I see, so if you never delete Pods, only create them, after a couple of ungraceful shutdowns (not giving pods a chance to evacuate), you would end up with many disconnected interfaces.

Would you be willing to follow-up on https://github.com/k8snetworkplumbingwg/ovs-cni/pull/109 and add the needed cleanup and a test for it?

**Comment by ykulazhenkov** [comment]
the issue should be fixed by https://github.com/k8snetworkplumbingwg/ovs-cni/pull/304

**Comment by phoracek** [comment]
Thanks you @ykulazhenkov. Closing this Issue. Anybody feel free to re-open this if the issue still occurs
