### ISSUE TITLE
Support for probes for ovs cni marker

### ISSUE THREAD

**Issue by rthakur-est** [k8snetworkplumbingwg/ovs-cni#230]
We have a requirement where we want to monitor ovs-cni-marker for liveness so that it can restarted in case of process hangs/failures.

**Comment by rthakur-est** [comment]
kind/enhancement

**Comment by rthakur-est** [comment]
One simple approach that can be pursued is to have a simple http endpoint for replying to liveness probe.
Is there any alternative way that can be used here?

**Comment by phoracek** [comment]
Hello @rthakur-est, HTTP server would be ok. Or even a simple [file-based liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command).

Would you be willing to extend the deployment manifest with it, and add a one of the probes?

**Comment by rthakur-est** [comment]
Hi @phoracek 
I will work on it.
