### ISSUE TITLE
Can ping but iperf fails

### ISSUE THREAD

**Issue by niloysh** [k8snetworkplumbingwg/ovs-cni#264]
Setup everything following demo.md. Ping is working fine, but iperf gives 0 Mbps.
Also mentioned in #145 but no solution given

**Comment by phoracek** [comment]
Hello @niloysh, that's surprising. Is iperf workink for you when you run it over a different CNI? For example the default pod network. I'd like to see if this issue is caused by the CNI or other environmental issues.

**Comment by niloysh** [comment]
Hello @phoracek

Pods have another interface with flannel as the CNI (default pod network). Iperf3 works fine with this interface.

OVS bridges on the nodes are connected using VXLAN overlay as mentioned in [demo.md ](https://github.com/k8snetworkplumbingwg/ovs-cni/blob/main/docs/demo.md#connect-bridges-using-vxlan)

If pods are in two different nodes - iperf3 fails. However, ping does work.
If pods are on the same node, iperf3 works!

There does not seem to be any issue with the VXLAN overlay, as I created separate interfaces on them (not using containers) and iperf3 tests worked fine.

**Comment by niloysh** [comment]
Turns out it was an issue with the MSS in iperf3.  Reducing the MSS (using the `-M` flag in iperf3) fixes the issue. Perhaps someone can shed some light on the the MSS calculation, but the maximum working MSS appears to be `1414`.

<img width="709" alt="Screenshot 2023-03-16 at 11 55 10 PM" src="https://user-images.githubusercontent.com/31400952/225811104-e36ce967-b790-46c2-92ea-1a233104f9e3.png">
