### ISSUE TITLE
Request to release a new version of ovs-cni

### ISSUE THREAD

**Issue by ykulazhenkov** [k8snetworkplumbingwg/ovs-cni#312]
Hi,

I would like to request a new release of ovs-cni (the first release which will use GitHub registry).

The following PRs with fixes/new features were merged recently:

https://github.com/k8snetworkplumbingwg/ovs-cni/pull/305
https://github.com/k8snetworkplumbingwg/ovs-cni/pull/307
https://github.com/k8snetworkplumbingwg/ovs-cni/pull/304
https://github.com/k8snetworkplumbingwg/ovs-cni/pull/302
https://github.com/k8snetworkplumbingwg/ovs-cni/pull/301

@phoracek @SchSeba

**Comment by phoracek** [comment]
@ykulazhenkov hello, sure thing.

https://github.com/k8snetworkplumbingwg/ovs-cni/releases/tag/v0.33.0

**Comment by phoracek** [comment]
@ykulazhenkov the multi-arch build seems to be stuck https://github.com/k8snetworkplumbingwg/ovs-cni/actions/runs/9282653448/job/25541137056

**Comment by ykulazhenkov** [comment]
> @ykulazhenkov the multi-arch build seems to be stuck https://github.com/k8snetworkplumbingwg/ovs-cni/actions/runs/9282653448/job/25541137056

@phoracek I see.
I think this is not related to our code. Let's try to restart the job. I don't have permissions to do this. Can you cancel the run and  re-run the job?

**Comment by phoracek** [comment]
@ykulazhenkov sounds good, let me give it a try https://github.com/k8snetworkplumbingwg/ovs-cni/actions/runs/9282653448/job/25553693255

**Comment by ykulazhenkov** [comment]
Hmm, strange... it looks like the job is stuck again (on a different step). 
I tried to run release job on my fork and it succeed https://github.com/ykulazhenkov/ovs-cni/actions/runs/9287042896/job/25555115854. 
I think this is an infrastructure related issue, maybe it is better to retry a bit later.

**Comment by phoracek** [comment]
@ykulazhenkov today was our lucky day!

https://github.com/k8snetworkplumbingwg/ovs-cni/actions/runs/9282653448/job/25596147017
ghcr.io/k8snetworkplumbingwg/ovs-cni-plugin:v0.33.0
