### ISSUE TITLE
How to deal with Pod-to-Service traffic

### ISSUE THREAD

**Issue by SMALL-head** [k8snetworkplumbingwg/ovs-cni#335]
We know that kubernetes uses iptables to change the serviceIP to the real Pod IP(which is known as DNAT), but when the traffic goes back from the Pod, kubernetes doesn't make something like SNAT, which will lead to RST when establishing TCP connection. So I wonder how to use ovs to handle this trouble. Like adding some conntrack openflow rule?

**Comment by phoracek** [comment]
Hello. That is outside of the scope of this CNI plugin. OVS CNI is only responsible for L2 connectivity between the pod and the selected OVS bridge. Furthermore, OVS CNI is not meant to be used for the default pod network (the one where service IPs are handled). What you describe sounds more relevant to a primary pod network CNI.
