### ISSUE TITLE
request a new release of ovs-cni

### ISSUE THREAD

**Issue by ykulazhenkov** [k8snetworkplumbingwg/ovs-cni#338]
v0.35.0 has an issue with multiarch images. The release images are meant to be multiarch, but all contain x86_64 binaries, making them unusable on non-x86_64 platforms.

see https://github.com/k8snetworkplumbingwg/ovs-cni/issues/260#issuecomment-2495530500 for details

https://github.com/k8snetworkplumbingwg/ovs-cni/pull/336 fixed the issue

I propose to release v0.35.1 to make multiarch images available for the latest released version

cc @phoracek @SchSeba

**Comment by ashokpariya0** [comment]
Please include the changes from PR [[#337](https://github.com/k8snetworkplumbingwg/ovs-cni/pull/337)](https://github.com/k8snetworkplumbingwg/ovs-cni/pull/337) as well. This will help us test on the s390x architecture as well. Thanks in advance!  @phoracek @oshoval

**Comment by oshoval** [comment]
Lets wait first for 337 indeed please
Thanks you all for your great effort

**Comment by phoracek** [comment]
I have now published https://github.com/k8snetworkplumbingwg/ovs-cni/releases/tag/v0.36.0. The images should be available  soon. Thank you all!

**Comment by ashokpariya0** [comment]
> I have now published https://github.com/k8snetworkplumbingwg/ovs-cni/releases/tag/v0.36.0. The images should be available soon. Thank you all!
>
@phoracek  Thanks a lot! Just wanted to update you: I performed a basic sanity check on the latest released image (ghcr.io/k8snetworkplumbingwg/ovs-cni-plugin:v0.36.0) on s390x, and it looks good to me.
cc @oshoval

**Comment by phoracek** [comment]
Awesome, thanks a lot of checking and for the contribution. OVS CNI inside mainframe, that's pretty cool!

**Comment by oshoval** [comment]
Awesome
Thanks all
