### ISSUE TITLE
request a new release of ovs-cni

### ISSUE THREAD

**Issue by filanov** [k8snetworkplumbingwg/ovs-cni#340]
v0.36.0 doesn't have a feature that i need https://github.com/k8snetworkplumbingwg/ovs-cni/commit/dbf2164547421c44f958abc58ac8e141d841739e 

I propose to release v0.37.0 to support this feature.

**Comment by ykulazhenkov** [comment]
@phoracek can we cut a new release, please?

**Comment by phoracek** [comment]
Released https://github.com/k8snetworkplumbingwg/ovs-cni/releases/tag/v0.37.0
